/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import java.sql.ResultSet;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import marathon_2.Queries;
import marathon_2.Timer;

/**
 *
 * @author Mauro
 */
public class Register_User extends javax.swing.JFrame {

    Queries q;
    DefaultComboBoxModel combo;
    String[] codeCountries;
    
    /**
     * Creates new form Register_User
     */
    public Register_User() {
        initComponents();
        
        Timer t = new Timer(lbl_time);
        q = new Queries();
        combo = new DefaultComboBoxModel();
        
        int numCountries = q.countCountries();
        codeCountries = new String[numCountries];
        
        combo.addElement("Select Country");
        
        ResultSet countriesData = q.getCountries();
        int n = 0;
        
        try {
            while(countriesData.next()){
                codeCountries[n] = countriesData.getString("CountryCode");
                combo.addElement(countriesData.getString("CountryName"));
                n++;
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
        
        jcb_country.setModel(combo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btn_back = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lbl_time = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txt_email = new javax.swing.JTextField();
        txt_name = new javax.swing.JTextField();
        txt_lastname = new javax.swing.JTextField();
        txt_password = new javax.swing.JPasswordField();
        txt_password_again = new javax.swing.JPasswordField();
        jcb_gender = new javax.swing.JComboBox();
        jdc_dateBirth = new com.toedter.calendar.JDateChooser();
        jcb_country = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Marathon Skills 2016  - Register Runner");
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("MARATHON SKILLS 2016");

        btn_back.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        btn_back.setText("Back");
        btn_back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_back)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addContainerGap(237, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_back)
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        lbl_time.setFont(new java.awt.Font("Dialog", 2, 14)); // NOI18N
        lbl_time.setForeground(new java.awt.Color(255, 255, 255));
        lbl_time.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_time.setText("0d days 0h hours 0m minutes 0s seconds until to race starts!");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_time, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(lbl_time)
                .addContainerGap())
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setText("REGISTER RUNNER");

        jLabel3.setText("Email");

        jLabel4.setText("Password");

        jLabel5.setText("Password Again");

        jLabel6.setText("First Name");

        jLabel7.setText("Last Name");

        jLabel8.setText("Gender");

        jLabel9.setText("Date of Birth");

        jLabel10.setText("Country");

        jcb_gender.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Gender", "Male", "Female" }));

        jdc_dateBirth.setDateFormatString("yyyy-MM-dd");

        jcb_country.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Gender", "Male", "Female" }));

        jButton1.setText("Register");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(212, 212, 212))
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txt_name, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                            .addComponent(txt_email, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_password, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_password_again, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_lastname))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jcb_gender, 0, 153, Short.MAX_VALUE)
                    .addComponent(jdc_dateBirth, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jcb_country, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txt_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txt_password_again, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(jcb_gender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel9))
                            .addComponent(jdc_dateBirth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jcb_country, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txt_lastname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Start mr = new Start();
        mr.setVisible(true);
    }//GEN-LAST:event_btn_backActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Start mr = new Start();
        mr.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String email = txt_email.getText();
        String name = txt_name.getText();
        String lastname = txt_lastname.getText();
        String password = txt_password.getText();
        String password_again = txt_password_again.getText();
        String gender = jcb_gender.getSelectedItem().toString();

        int numberCharacteresUppercase = 0;
        int numberDigits = 0;
        int numberCharacters = 0;
        boolean validEmail = false;
        int step1 = 0;
        int step2 = 0;

        // validate email
        for (int i = 0; i < email.length(); i++) {
            if(
                    email.charAt(i) == '@' 
            ){
                step1++;
            }
            
            if(
                    email.charAt(i) == '.'
            ){
                step2++;
            }
            
            if(step1 > 0 && step2 > 0)
                validEmail = true;
        }
        
        // validate password
        for (int i = 0; i < password.length(); i++) {
            if(Character.isUpperCase(password.charAt(i))){
                numberCharacteresUppercase++;
            }

            if(Character.isDigit(password.charAt(i))){
                numberDigits++;
            }

            if(
                    password.charAt(i) == '!' || 
                    password.charAt(i) == '@' || 
                    password.charAt(i) == '#' || 
                    password.charAt(i) == '$' || 
                    password.charAt(i) == '%' || 
                    password.charAt(i) == '^'
            ){
                numberCharacters++;
            }
        }
        
        String dateBirth = "";
        int currentYear = 2016;
        int yearBirth = 0;
        
        try{
            String[] partsDate = jdc_dateBirth.getDate().toLocaleString().split(" ")[0].split("/");
            dateBirth = partsDate[2]+"-"+partsDate[1]+"-"+partsDate[0];
            yearBirth = Integer.parseInt(partsDate[2]);
        }catch(Exception e){
            System.out.println(e.getMessage());
        }
        
        if("".equals(email)){
            JOptionPane.showMessageDialog(this, "The email can't be empty!", "Marathon Skills 2016", JOptionPane.WARNING_MESSAGE);
            txt_email.requestFocus();
        }else if(validEmail == false){
            JOptionPane.showMessageDialog(this, "The email isn't valid!", "Marathon Skills 2016", JOptionPane.WARNING_MESSAGE);
            txt_email.requestFocus();
        }else if(q.verifyEmail(email)){
            JOptionPane.showMessageDialog(this, "The email already is register!", "Marathon Skills 2016", JOptionPane.WARNING_MESSAGE);
            txt_email.requestFocus();
        }else if(password.length() < 6){
            JOptionPane.showMessageDialog(this, "The password is invalid, must be major to 6 characteres!", "Marathon Skills 2016", JOptionPane.WARNING_MESSAGE);
            txt_password.requestFocus();
        }else if(numberCharacteresUppercase < 1){
            JOptionPane.showMessageDialog(this, "The password require minimun one letter in uppercase!", "Marathon Skills 2016", JOptionPane.WARNING_MESSAGE);
            txt_password.requestFocus();
        }else if(numberDigits < 1){
            JOptionPane.showMessageDialog(this, "The password require minimun one digit o number!", "Marathon Skills 2016", JOptionPane.WARNING_MESSAGE);
            txt_password.requestFocus();
        }else if(numberCharacters < 1){
            JOptionPane.showMessageDialog(this, "Verify if the password contains some of this characteres '!@#$%^'!", "Marathon Skills 2016", JOptionPane.WARNING_MESSAGE);
            txt_password.requestFocus();
        }else if("".equals(name)){
            JOptionPane.showMessageDialog(this, "The name can't be empty!", "Marathon Skills 2016", JOptionPane.WARNING_MESSAGE);
            txt_name.requestFocus();
        }else if("".equals(lastname)){
            JOptionPane.showMessageDialog(this, "The lastname can't be empty!", "Marathon Skills 2016", JOptionPane.WARNING_MESSAGE);
            txt_lastname.requestFocus();
        }else if(jcb_gender.getSelectedIndex() == 0){
            JOptionPane.showMessageDialog(this, "Select first one gender!", "Marathon Skills 2016", JOptionPane.WARNING_MESSAGE);
            jcb_gender.requestFocus();
        }else if("".equals(dateBirth)){
            JOptionPane.showMessageDialog(this, "The date of birth can't be empty!", "Marathon Skills 2016", JOptionPane.WARNING_MESSAGE);
            jdc_dateBirth.getDateEditor().getUiComponent().requestFocus();
        }else if((currentYear - yearBirth) < 10){
            JOptionPane.showMessageDialog(this, "your age must be major to 10 years old!", "Marathon Skills 2016", JOptionPane.WARNING_MESSAGE);
            jdc_dateBirth.getDateEditor().getUiComponent().requestFocus();
        }else if(jcb_country.getSelectedIndex() == 0){
            JOptionPane.showMessageDialog(this, "Select first one country!", "Marathon Skills 2016", JOptionPane.WARNING_MESSAGE);
            jcb_country.requestFocus();
        }else{
            if(password.equals(password_again)){
                boolean response = q.registerUser(email, password, name, lastname, gender, dateBirth, codeCountries[jcb_country.getSelectedIndex() - 1]);

                if(response){
                    JOptionPane.showMessageDialog(this, "Register Succesfull!", "Marathon Skills 2016", JOptionPane.INFORMATION_MESSAGE);
                    this.setVisible(false);
                    Views.Home h = new Views.Home();
                    h.txt_email.setText(email);
                    h.setVisible(true);
                    
                }else{
                    JOptionPane.showMessageDialog(this, "Error!", "Marathon Skills 2016", JOptionPane.WARNING_MESSAGE);
                }
            }else{
                JOptionPane.showMessageDialog(this, "The passwords are not equals!", "Marathon Skills 2016", JOptionPane.WARNING_MESSAGE);
                txt_password.requestFocus();
            }
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register_User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register_User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register_User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register_User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register_User().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_back;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JComboBox jcb_country;
    private javax.swing.JComboBox jcb_gender;
    private com.toedter.calendar.JDateChooser jdc_dateBirth;
    private javax.swing.JLabel lbl_time;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_lastname;
    private javax.swing.JTextField txt_name;
    private javax.swing.JPasswordField txt_password;
    private javax.swing.JPasswordField txt_password_again;
    // End of variables declaration//GEN-END:variables
}
